### ISSUE TITLE
get error message "TypeError: Cannot read property 'csrftoken' of undefined"

### ISSUE THREAD

**Issue by dbloms** [ashishmadeti/spotify-playlist-downloader#13]
Hello,

I'm using debian buster and get the following error message, when I start this programm.

```
Downloader App Started..
/usr/local/lib/node_modules/spotify-playlist-downloader/node_modules/spotify-web/lib/spotify.js:256
  debug('login CSRF token: %j, tracking ID: %j', args.csrftoken, args.trackingId);
                                                      ^

TypeError: Cannot read property 'csrftoken' of undefined
    at Spotify._onsecret (/usr/local/lib/node_modules/spotify-playlist-downloader/node_modules/spotify-web/lib/spotify.js:256:55)
    at Request.callback (/usr/local/lib/node_modules/spotify-playlist-downloader/node_modules/superagent/lib/node/index.js:584:30)
    at Request.<anonymous> (/usr/local/lib/node_modules/spotify-playlist-downloader/node_modules/superagent/lib/node/index.js:133:10)
    at Request.emit (events.js:194:15)
    at Request.EventEmitter.emit (domain.js:441:20)
    at Stream.<anonymous> (/usr/local/lib/node_modules/spotify-playlist-downloader/node_modules/superagent/lib/node/index.js:714:12)
    at Stream.emit (events.js:194:15)
    at Stream.EventEmitter.emit (domain.js:441:20)
    at Unzip.<anonymous> (/usr/local/lib/node_modules/spotify-playlist-downloader/node_modules/superagent/lib/node/utils.js:120:12)
    at Unzip.emit (events.js:194:15)
    at Unzip.EventEmitter.emit (domain.js:441:20)
    at endReadableNT (_stream_readable.js:1103:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```
can you see what's wrong here ?

**Comment by ashishmadeti** [comment]
@dbloms Can you please post the following information?
1. The command you ran.
2. Output of `python -V` and `python3 -V`

**Comment by ashishmadeti** [comment]
@dbloms Are you sure you posted the issue in the correct repo? As I can see that the crash is related to JS but this repo uses only Python.

**Comment by dbloms** [comment]
@ashishmadeti you are right.
I tried more different programms and so made the issue in your repo.
Sorry for that
